name: 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: rounak-au
      - name: Commit & Push
        run: |
          git config user.email "rounak.au@gmail.com"
          git config user.name "rounak-au"
          git add -A .
          git commit -m "Generated 3D contribution calendar"
          git push
